title: Digital Death

email: sam.butler@finance.nsw.gov.au
description: >- # this means to ignore newlines until "baseurl:"
  Simple explaination of the product or service.
baseurl: "/DigitalDeath" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tjharrop
github_username:  tjharrop

browserTitle: Digital Death

stage: prototype

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

remote_theme: tjharrop/NSW-jekyll-theme
